---
abstract: 'Determine VPSes and cloud hosting machines via their IP address'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  AnyEvent::Future: '0'
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IP-CloudHoster
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '5'
  Filter::signatures: '0.09'
  Future: '0'
  Future::HTTP: '0.06'
  JSON: '0'
  JSON::PP: '0'
  Module::Pluggable: '0'
  Moo: '2'
  Net::IRR: '0'
  Net::Netmask: '0'
  perl: '5.006'
resources:
  repository: git://github.com/Corion/IP-CloudHoster.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
